name: ArcGIS Auto Register

on:
  workflow_dispatch:
  repository_dispatch:
    types: [arcgis-register]

jobs:
  register:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Chrome
        run: |
            sudo apt-get update
            sudo apt-get install -y wget gnupg unzip
            wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
            echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
            sudo apt-get update
            sudo apt-get install -y google-chrome-stable
            google-chrome --version

      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          pip install undetected-chromedriver selenium requests

      - name: Run ArcGIS auto register
        env:
          TEMPMail_API_URL: ${{ secrets.TEMPMail_API_URL }}
          TEMPMail_TOKEN: ${{ secrets.TEMPMail_TOKEN }}
          TEMPMail_DOMAIN: ${{ secrets.TEMPMail_DOMAIN }}
          CALLBACK_URL: ${{ secrets.WORKER_CALLBACK_URL }}
          CALLBACK_SECRET: ${{ secrets.WORKER_CALLBACK_SECRET }}
        run: |
          python3 arcgis_auto_register.py
